### ISSUE TITLE
Look at group J's project

### ISSUE THREAD

**Issue by Herover** [Herover/itu-devops-h#89]
[Stuff to check for](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_06/README_TASKS.md#3-software-maintenance-ii).

- Minitwit http://minitwit.waygroup.net/
- Github https://github.com/AlexBMJ/minitwit

**Comment by erentomurcuk** [comment]
Tests are done.

Given list:

- Do you see a public timeline? YES
- Does the public timeline show messages that the application received from the simulator? YES
- Can you create a new user? YES
- Can you login as a new user? YES
- Can you write a message? YES
- After publishing a message, does it appear on you private timeline? YES AND NO
- Can you follow another user? NO (Follow button is there but testing it isn't possible)

Found issues:

- Public timeline is user's own timeline when logged in. While logged in, public timeline button doesn't exist and user's timeline acts like the public timeline.
- Follow button is there but since the user does not have a timeline other tweets aren't separated so it's not possible to test until there is a working personal timeline.
